export function isSimulator(): boolean;
export function getAppId(): Promise<string>;
export function getAppIdSync(): string;
export function getVersionName(): Promise<string>;
export function getVersionNameSync(): string;
export function getAppName(): Promise<string>;
export function getAppNameSync(): string;
export function getBuildNumber(): Promise<number>;
export function getBuildNumberSync(): number;
